#include "chip/i8080_impl.h"

static Cstr         i8080_instruction_names[256] = {
    "nop       ", "lxi  BC,##", "stax BC   ", "inx  BC   ",
    "inr  B    ", "dcr  B    ", "mvi  B,#  ", "rlc       ",
    "---- ---  ", "dad  BC   ", "ldax BC   ", "dcx  BC   ",
    "inr  C    ", "dcr  C    ", "mvi  C,#  ", "rrc       ",
    "---- ---  ", "lxi  DE,##", "stax DE   ", "inx  DE   ",
    "inr  D    ", "dcr  D    ", "mvi  D,#  ", "ral       ",
    "---- ---  ", "dad  DE   ", "ldax DE   ", "dcx  DE   ",
    "inr  E    ", "dcr  E    ", "mvi  E,#  ", "rar       ",
    "---- ---  ", "lxi  HL,##", "shld ##   ", "inx  HL   ",
    "inr  H    ", "dcr  H    ", "mvi  H,#  ", "daa       ",
    "---- ---  ", "dad  HL   ", "lhld ##   ", "dcx  HL   ",
    "inr  L    ", "dcr  L    ", "mvi  L,#  ", "cma       ",
    "---- ---  ", "lxi  SP,##", "sta  ##   ", "inx  SP   ",
    "inr  M    ", "dcr  M    ", "mvi  M,#  ", "stc       ",
    "---- ---  ", "dad  SP   ", "lda  ##   ", "dcx  SP   ",
    "inr  A    ", "dcr  A    ", "mvi  A,#  ", "cmc       ",
    "mov  B,B  ", "mov  B,C  ", "mov  B,D  ", "mov  B,E  ",
    "mov  B,H  ", "mov  B,L  ", "mov  B,M  ", "mov  B,A  ",
    "mov  C,B  ", "mov  C,C  ", "mov  C,D  ", "mov  C,E  ",
    "mov  C,H  ", "mov  C,L  ", "mov  C,M  ", "mov  C,A  ",
    "mov  D,B  ", "mov  D,C  ", "mov  D,D  ", "mov  D,E  ",
    "mov  D,H  ", "mov  D,L  ", "mov  D,M  ", "mov  D,A  ",
    "mov  E,B  ", "mov  E,C  ", "mov  E,D  ", "mov  E,E  ",
    "mov  E,H  ", "mov  E,L  ", "mov  E,M  ", "mov  E,A  ",
    "mov  H,B  ", "mov  H,C  ", "mov  H,D  ", "mov  H,E  ",
    "mov  H,H  ", "mov  H,L  ", "mov  H,M  ", "mov  H,A  ",
    "mov  L,B  ", "mov  L,C  ", "mov  L,D  ", "mov  L,E  ",
    "mov  L,H  ", "mov  L,L  ", "mov  L,M  ", "mov  L,A  ",
    "mov  M,B  ", "mov  M,C  ", "mov  M,D  ", "mov  M,E  ",
    "mov  M,H  ", "mov  M,L  ", "hlt       ", "mov  M,A  ",
    "mov  A,B  ", "mov  A,C  ", "mov  A,D  ", "mov  A,E  ",
    "mov  A,H  ", "mov  A,L  ", "mov  A,M  ", "mov  A,A  ",
    "add  B    ", "add  C    ", "add  D    ", "add  E    ",
    "add  H    ", "add  L    ", "add  M    ", "add  A    ",
    "adc  B    ", "adc  C    ", "adc  D    ", "adc  E    ",
    "adc  H    ", "adc  L    ", "adc  M    ", "adc  A    ",
    "sub  B    ", "sub  C    ", "sub  D    ", "sub  E    ",
    "sub  H    ", "sub  L    ", "sub  M    ", "sub  A    ",
    "sbb  B    ", "sbb  C    ", "sbb  D    ", "sbb  E    ",
    "sbb  H    ", "sbb  L    ", "sbb  M    ", "sbb  A    ",
    "ana  B    ", "ana  C    ", "ana  D    ", "ana  E    ",
    "ana  H    ", "ana  L    ", "ana  M    ", "ana  A    ",
    "xra  B    ", "xra  C    ", "xra  D    ", "xra  E    ",
    "xra  H    ", "xra  L    ", "xra  M    ", "xra  A    ",
    "ora  B    ", "ora  C    ", "ora  D    ", "ora  E    ",
    "ora  H    ", "ora  L    ", "ora  M    ", "ora  A    ",
    "cmp  B    ", "cmp  C    ", "cmp  D    ", "cmp  E    ",
    "cmp  H    ", "cmp  L    ", "cmp  M    ", "cmp  A    ",
    "rnz       ", "pop  BC   ", "jnz  ##   ", "jmp  ##   ",
    "cnz  ##   ", "push BC   ", "adi  #    ", "rst  0    ",
    "rz        ", "ret       ", "jz   ##   ", "---- ---  ",
    "cz   ##   ", "call ##   ", "aci  #    ", "rst  1    ",
    "rnc       ", "pop  DE   ", "jnc  ##   ", "out  #    ",
    "cnc  ##   ", "push DE   ", "sui  #    ", "rst  2    ",
    "rc        ", "---- ---  ", "jc   ##   ", "in   #    ",
    "cc   ##   ", "---- ---  ", "sbi  #    ", "rst  3    ",
    "rpo       ", "pop  HL   ", "jpo  ##   ", "xthl      ",
    "cpo  ##   ", "push HL   ", "ani  #    ", "rst  4    ",
    "rpe       ", "pchl      ", "jpe  ##   ", "xchg      ",
    "cpe  ##   ", "---- ---  ", "xri  #    ", "rst  5    ",
    "rp        ", "pop  PSW  ", "jp   ##   ", "di        ",
    "cp   ##   ", "push PSW  ", "ori  #    ", "rst  6    ",
    "rm        ", "sphl      ", "jm   ##   ", "ei        ",
    "cm   ##   ", "---- ---  ", "cpi  #    ", "rst  7    ",
};

Cstr i8080_instruction_name(Byte op)
{
    return i8080_instruction_names[op];
}

static Word         i8080_instruction_lens[256] = {
    1, 3, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1,
    1, 3, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1,
    1, 3, 3, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 2, 1,
    1, 3, 3, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 2, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 3, 3, 3, 1, 2, 1, 1, 1, 3, 1, 3, 3, 2, 1,
    1, 1, 3, 2, 3, 1, 2, 1, 1, 1, 3, 2, 3, 1, 2, 1,
    1, 1, 3, 1, 3, 1, 2, 1, 1, 1, 3, 1, 3, 1, 2, 1,
    1, 1, 3, 1, 3, 1, 2, 1, 1, 1, 3, 1, 3, 1, 2, 1,
};

Word i8080_instruction_len(Byte op)
{
    return i8080_instruction_lens[op];
}

static Cstr         i8080_instruction_4asms[256] = {
    "          NOP, ", "0x####  B LXI, ", "        B STAX,", "        B INX, ",
    "        B INR, ", "        B DCR, ", "0x##    B MVI, ", "          RLC, ",
    "     0x08 C,   ", "        B DAD, ", "        B LDAX,", "        B DCX, ",
    "        C INR, ", "        C DCR, ", "0x##    C MVI, ", "          RRC, ",
    "     0x10 C,   ", "0x####  D LXI, ", "        D STAX,", "        D INX, ",
    "        D INR, ", "        D DCR, ", "0x##    D MVI, ", "          RAL, ",
    "     0x18 C,   ", "        D DAD, ", "        D LDAX,", "        D DCX, ",
    "        E INR, ", "        E DCR, ", "0x##    E MVI, ", "          RAR, ",
    "     0x20 C,   ", "0x####  H LXI, ", "0x####    SHLD,", "        H INX, ",
    "        H INR, ", "        H DCR, ", "0x##    H MVI, ", "          DAA, ",
    "     0x28 C,   ", "        H DAD, ", "0x####    LHLD,", "        H DCX, ",
    "        L INR, ", "        L DCR, ", "0x##    L MVI, ", "          CMA, ",
    "     0x30 C,   ", "0x#### SP LXI, ", "0x####    STA, ", "       SP INX, ",
    "        M INR, ", "        M DCR, ", "0x##    M MVI, ", "          STC, ",
    "     0x38 C,   ", "       SP DAD, ", "0x####    LDA, ", "       SP DCX, ",
    "        A INR, ", "        A DCR, ", "0x##    A MVI, ", "          CMC, ",
    "      B B MOV, ", "      C B MOV, ", "      D B MOV, ", "      E B MOV, ",
    "      H B MOV, ", "      L B MOV, ", "      M B MOV, ", "      A B MOV, ",
    "      B C MOV, ", "      C C MOV, ", "      D C MOV, ", "      E C MOV, ",
    "      H C MOV, ", "      L C MOV, ", "      M C MOV, ", "      A C MOV, ",
    "      B D MOV, ", "      C D MOV, ", "      D D MOV, ", "      E D MOV, ",
    "      H D MOV, ", "      L D MOV, ", "      M D MOV, ", "      A D MOV, ",
    "      B E MOV, ", "      C E MOV, ", "      D E MOV, ", "      E E MOV, ",
    "      H E MOV, ", "      L E MOV, ", "      M E MOV, ", "      A E MOV, ",
    "      B H MOV, ", "      C H MOV, ", "      D H MOV, ", "      E H MOV, ",
    "      H H MOV, ", "      L H MOV, ", "      M H MOV, ", "      A H MOV, ",
    "      B L MOV, ", "      C L MOV, ", "      D L MOV, ", "      E L MOV, ",
    "      H L MOV, ", "      L L MOV, ", "      M L MOV, ", "      A L MOV, ",
    "      B M MOV, ", "      C M MOV, ", "      D M MOV, ", "      E M MOV, ",
    "      H M MOV, ", "      L M MOV, ", "          HLT, ", "      A M MOV, ",
    "      B A MOV, ", "      C A MOV, ", "      D A MOV, ", "      E A MOV, ",
    "      H A MOV, ", "      L A MOV, ", "      M A MOV, ", "      A A MOV, ",
    "        B ADD, ", "        C ADD, ", "        D ADD, ", "        E ADD, ",
    "        H ADD, ", "        L ADD, ", "        M ADD, ", "        A ADD, ",
    "        B ADC, ", "        C ADC, ", "        D ADC, ", "        E ADC, ",
    "        H ADC, ", "        L ADC, ", "        M ADC, ", "        A ADC, ",
    "        B SUB, ", "        C SUB, ", "        D SUB, ", "        E SUB, ",
    "        H SUB, ", "        L SUB, ", "        M SUB, ", "        A SUB, ",
    "        B SBB, ", "        C SBB, ", "        D SBB, ", "        E SBB, ",
    "        H SBB, ", "        L SBB, ", "        M SBB, ", "        A SBB, ",
    "        B ANA, ", "        C ANA, ", "        D ANA, ", "        E ANA, ",
    "        H ANA, ", "        L ANA, ", "        M ANA, ", "        A ANA, ",
    "        B XRA, ", "        C XRA, ", "        D XRA, ", "        E XRA, ",
    "        H XRA, ", "        L XRA, ", "        M XRA, ", "        A XRA, ",
    "        B ORA, ", "        C ORA, ", "        D ORA, ", "        E ORA, ",
    "        H ORA, ", "        L ORA, ", "        M ORA, ", "        A ORA, ",
    "        B CMP, ", "        C CMP, ", "        D CMP, ", "        E CMP, ",
    "        H CMP, ", "        L CMP, ", "        M CMP, ", "        A CMP, ",
    "          RNZ, ", "        B POP, ", "0x####    JNZ, ", "0x####    JMP, ",
    "0x####    CNZ, ", "        B PUSH,", "0x##      ADI, ", "        0 RST, ",
    "          RZ,  ", "          RET, ", "0x####    JZ,  ", "     0xCB C,   ",
    "0x####    CZ,  ", "0x####    CALL,", "0x##      ACI, ", "        1 RST, ",
    "          RNC, ", "        D POP, ", "0x####    JNC, ", "0x##      OUT, ",
    "0x####    CNC, ", "        D PUSH,", "0x##      SUI, ", "        2 RST, ",
    "          RC,  ", "     0xD9 C,   ", "0x####    JC,  ", "0x##      IN,  ",
    "0x####    CC,  ", "     0xDD C,   ", "0x##      SBI, ", "        3 RST, ",
    "          RPO, ", "        H POP, ", "0x####    JPO, ", "          XTHL,",
    "0x####    CPO, ", "        H PUSH,", "0x##      ANI, ", "        4 RST, ",
    "          RPE, ", "          PCHL,", "0x####    JPE, ", "          XCHG,",
    "0x####    CPE, ", "     0xED C,   ", "0x##      XRI, ", "        5 RST, ",
    "          RP,  ", "      PSW POP, ", "0x####    JP,  ", "          DI,  ",
    "0x####    CP,  ", "      PSW PUSH,", "0x##      ORI, ", "        6 RST, ",
    "          RM,  ", "          SPHL,", "0x####    JM,  ", "          EI,  ",
    "0x####    CM,  ", "     0xFD C,   ", "0x##      CPI, ", "        7 RST, ",
};

Cstr i8080_instruction_4asm(Byte op)
{
    return i8080_instruction_4asms[op];
}
