#include "i8080_impl.h"

static Cstr         i8080_instruction_names[256] = {
    "nop       ", "lxi  BC,##", "stax BC,##", "inx  BC   ",
    "inr  B    ", "dcr  B    ", "mvi  B,#  ", "rlc       ",
    "---- ---  ", "dad  BC   ", "ldax BC,##", "dcx  BC   ",
    "inr  C    ", "dcr  C    ", "mvi  C,#  ", "rrc       ",
    "---- ---  ", "lxi  DE,##", "stax DE,##", "inx  DE   ",
    "inr  D    ", "dcr  D    ", "mvi  D,#  ", "ral       ",
    "---- ---  ", "dad  DE   ", "ldax DE,##", "dcx  DE   ",
    "inr  E    ", "dcr  E    ", "mvi  E,#  ", "rar       ",
    "---- ---  ", "lxi  HL,##", "shld ##   ", "inx  HL   ",
    "inr  H    ", "dcr  H    ", "mvi  H,#  ", "daa       ",
    "---- ---  ", "dad  HL   ", "lhld ##   ", "dcx  HL   ",
    "inr  L    ", "dcr  L    ", "mvi  L,#  ", "cma       ",
    "---- ---  ", "lxi  SP,##", "sta  ##   ", "inx  SP   ",
    "inr  M    ", "dcr  M    ", "mvi  M,#  ", "stc       ",
    "---- ---  ", "dad  SP   ", "lda  ##   ", "dcx  SP   ",
    "inr  A    ", "dcr  A    ", "mvi  A,#  ", "cmc       ",
    "mov  B,B  ", "mov  B,C  ", "mov  B,D  ", "mov  B,E  ",
    "mov  B,H  ", "mov  B,L  ", "mov  B,M  ", "mov  B,A  ",
    "mov  C,B  ", "mov  C,C  ", "mov  C,D  ", "mov  C,E  ",
    "mov  C,H  ", "mov  C,L  ", "mov  C,M  ", "mov  C,A  ",
    "mov  D,B  ", "mov  D,C  ", "mov  D,D  ", "mov  D,E  ",
    "mov  D,H  ", "mov  D,L  ", "mov  D,M  ", "mov  D,A  ",
    "mov  E,B  ", "mov  E,C  ", "mov  E,D  ", "mov  E,E  ",
    "mov  E,H  ", "mov  E,L  ", "mov  E,M  ", "mov  E,A  ",
    "mov  H,B  ", "mov  H,C  ", "mov  H,D  ", "mov  H,E  ",
    "mov  H,H  ", "mov  H,L  ", "mov  H,M  ", "mov  H,A  ",
    "mov  L,B  ", "mov  L,C  ", "mov  L,D  ", "mov  L,E  ",
    "mov  L,H  ", "mov  L,L  ", "mov  L,M  ", "mov  L,A  ",
    "mov  M,B  ", "mov  M,C  ", "mov  M,D  ", "mov  M,E  ",
    "mov  M,H  ", "mov  M,L  ", "hlt       ", "mov  M,A  ",
    "mov  A,B  ", "mov  A,C  ", "mov  A,D  ", "mov  A,E  ",
    "mov  A,H  ", "mov  A,L  ", "mov  A,M  ", "mov  A,A  ",
    "add  B    ", "add  C    ", "add  D    ", "add  E    ",
    "add  H    ", "add  L    ", "add  M    ", "add  A    ",
    "adc  B    ", "adc  C    ", "adc  D    ", "adc  E    ",
    "adc  H    ", "adc  L    ", "adc  M    ", "adc  A    ",
    "sub  B    ", "sub  C    ", "sub  D    ", "sub  E    ",
    "sub  H    ", "sub  L    ", "sub  M    ", "sub  A    ",
    "sbb  B    ", "sbb  C    ", "sbb  D    ", "sbb  E    ",
    "sbb  H    ", "sbb  L    ", "sbb  M    ", "sbb  A    ",
    "ana  B    ", "ana  C    ", "ana  D    ", "ana  E    ",
    "ana  H    ", "ana  L    ", "ana  M    ", "ana  A    ",
    "xra  B    ", "xra  C    ", "xra  D    ", "xra  E    ",
    "xra  H    ", "xra  L    ", "xra  M    ", "xra  A    ",
    "ora  B    ", "ora  C    ", "ora  D    ", "ora  E    ",
    "ora  H    ", "ora  L    ", "ora  M    ", "ora  A    ",
    "cmp  B    ", "cmp  C    ", "cmp  D    ", "cmp  E    ",
    "cmp  H    ", "cmp  L    ", "cmp  M    ", "cmp  A    ",
    "rnz       ", "pop  BC   ", "jnz  ##   ", "jmp  ##   ",
    "cnz  ##   ", "push BC   ", "adi  #    ", "rst  0    ",
    "rz        ", "ret       ", "jz   ##   ", "---- ---  ",
    "cz   ##   ", "call ##   ", "aci  #    ", "rst  1    ",
    "rnc       ", "pop  DE   ", "jnc  ##   ", "out  #    ",
    "cnc  ##   ", "push DE   ", "sui  #    ", "rst  2    ",
    "rc        ", "---- ---  ", "jc   ##   ", "in   #    ",
    "cc   ##   ", "---- ---  ", "sbi  #    ", "rst  3    ",
    "rpo       ", "pop  HL   ", "jpo  ##   ", "xthl      ",
    "cpo  ##   ", "push HL   ", "ani  #    ", "rst  4    ",
    "rpe       ", "pchl      ", "jpe  ##   ", "xchg      ",
    "cpe  ##   ", "---- ---  ", "xri  #    ", "rst  5    ",
    "rp        ", "pop  PSW  ", "jp   ##   ", "di        ",
    "cp   ##   ", "push PSW  ", "ori  #    ", "rst  6    ",
    "rm        ", "sphl      ", "jm   ##   ", "ei        ",
    "cm   ##   ", "---- ---  ", "cpi  #    ", "rst  7    ",
};

Cstr i8080_instruction_name(Byte op)
{
    return i8080_instruction_names[op];
}
